/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PdfTagsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  companionFolder: "_pdf-tags"
};

// src/SettingsTab.ts
var import_obsidian = require("obsidian");
var PdfTagsSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Companion folder").setDesc(
      "Vault-relative folder where companion .md files (holding tags) are stored. These files are what Obsidian indexes for graph view and search."
    ).addText(
      (text) => text.setPlaceholder("_pdf-tags").setValue(this.plugin.settings.companionFolder).onChange(async (value) => {
        this.plugin.settings.companionFolder = value.trim() || "_pdf-tags";
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/PdfToolbarInjector.ts
var import_obsidian3 = require("obsidian");

// src/TagPopover.ts
var import_obsidian2 = require("obsidian");
var TagPopover = class {
  constructor(plugin, file, anchorEl, onClose) {
    this.containerEl = null;
    this.onOutsideClick = (evt) => {
      if (this.containerEl && !this.containerEl.contains(evt.target) && !this.anchorEl.contains(evt.target)) {
        this.close();
      }
    };
    this.plugin = plugin;
    this.file = file;
    this.anchorEl = anchorEl;
    this.onCloseCallback = onClose != null ? onClose : null;
  }
  open() {
    if (this.containerEl) {
      this.close();
      return;
    }
    void this.render();
  }
  close() {
    var _a, _b;
    (_a = this.containerEl) == null ? void 0 : _a.remove();
    this.containerEl = null;
    document.removeEventListener("mousedown", this.onOutsideClick);
    (_b = this.onCloseCallback) == null ? void 0 : _b.call(this);
  }
  async render() {
    const file = this.file;
    const tags = await this.plugin.getTagsForFile(file.path);
    const vaultTags = this.plugin.getAllVaultTags().filter((t) => !tags.includes(t));
    const pop = document.body.createEl("div", { cls: "pdf-tags-popover pdf-tags-popover--hidden" });
    this.containerEl = pop;
    const chipArea = pop.createEl("div", { cls: "pdf-tags-popover-chips" });
    this.renderChips(chipArea, tags, file.path);
    const inputRow = pop.createEl("div", { cls: "pdf-tags-input-row" });
    const input = inputRow.createEl("input", {
      type: "text",
      placeholder: "Add tag\u2026",
      cls: "pdf-tags-input"
    });
    const addBtn = inputRow.createEl("button", { cls: "pdf-tags-add-btn" });
    (0, import_obsidian2.setIcon)(addBtn, "plus");
    addBtn.setAttribute("aria-label", "Add tag");
    const dropdown = pop.createEl("div", { cls: "pdf-tags-dropdown" });
    const showDropdown = (query) => {
      dropdown.empty();
      if (!query) {
        dropdown.classList.remove("pdf-tags-dropdown--visible");
        return;
      }
      const q = query.toLowerCase().replace(/^#+/, "");
      const matches = vaultTags.filter((t) => t.toLowerCase().includes(q)).slice(0, 8);
      if (!matches.length) {
        dropdown.classList.remove("pdf-tags-dropdown--visible");
        return;
      }
      matches.forEach((tag) => {
        const item = dropdown.createEl("div", {
          cls: "pdf-tags-dropdown-item",
          text: `#${tag}`
        });
        item.addEventListener("mousedown", (e) => {
          e.preventDefault();
          input.value = "";
          dropdown.classList.remove("pdf-tags-dropdown--visible");
          void this.plugin.addTag(file.path, tag).then(() => this.rerender(pop, file));
        });
      });
      dropdown.classList.add("pdf-tags-dropdown--visible");
    };
    input.addEventListener("input", () => showDropdown(input.value));
    input.addEventListener("blur", () => {
      setTimeout(() => {
        dropdown.classList.remove("pdf-tags-dropdown--visible");
      }, 150);
    });
    const doAdd = () => {
      const raw = input.value.trim().replace(/^#+/, "");
      if (!raw)
        return;
      const tag = raw.toLowerCase().replace(/\s+/g, "-");
      input.value = "";
      dropdown.classList.remove("pdf-tags-dropdown--visible");
      void this.plugin.addTag(file.path, tag).then(() => this.rerender(pop, file));
    };
    addBtn.addEventListener("click", doAdd);
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        doAdd();
      if (e.key === "Escape")
        this.close();
    });
    if (vaultTags.length > 0) {
      const section = pop.createEl("div", { cls: "pdf-tags-suggestions" });
      section.createEl("p", { cls: "pdf-tags-suggestions-label", text: "Your tags:" });
      const list = section.createEl("div", { cls: "pdf-tags-suggestion-list" });
      vaultTags.slice(0, 20).forEach((tag) => {
        const chip = list.createEl("span", {
          cls: "pdf-tags-suggestion-chip",
          text: `#${tag}`
        });
        chip.addEventListener("click", () => {
          void this.plugin.addTag(file.path, tag).then(() => this.rerender(pop, file));
        });
      });
    }
    setTimeout(() => {
      document.addEventListener("mousedown", this.onOutsideClick);
    }, 0);
    setTimeout(() => input.focus(), 50);
    requestAnimationFrame(() => {
      this.positionPopover(pop);
      pop.classList.remove("pdf-tags-popover--hidden");
    });
  }
  positionPopover(pop) {
    const rect = this.anchorEl.getBoundingClientRect();
    const popW = pop.offsetWidth;
    const popH = pop.offsetHeight;
    const vw = window.innerWidth;
    const vh = window.innerHeight;
    const GAP = 4;
    let top = rect.bottom + GAP;
    if (top + popH > vh)
      top = rect.top - popH - GAP;
    if (top < 0)
      top = GAP;
    let left = rect.right - popW;
    if (left < GAP)
      left = GAP;
    if (left + popW > vw - GAP)
      left = vw - GAP - popW;
    pop.style.top = `${top}px`;
    pop.style.left = `${left}px`;
  }
  async rerender(pop, file) {
    const tags = await this.plugin.getTagsForFile(file.path);
    const chipArea = pop.querySelector(".pdf-tags-popover-chips");
    if (chipArea instanceof HTMLElement) {
      chipArea.empty();
      this.renderChips(chipArea, tags, file.path);
    }
    const suggestList = pop.querySelector(".pdf-tags-suggestion-list");
    if (suggestList instanceof HTMLElement) {
      const vaultTags = this.plugin.getAllVaultTags().filter((t) => !tags.includes(t));
      suggestList.empty();
      vaultTags.slice(0, 20).forEach((tag) => {
        const chip = suggestList.createEl("span", {
          cls: "pdf-tags-suggestion-chip",
          text: `#${tag}`
        });
        chip.addEventListener("click", () => {
          void this.plugin.addTag(file.path, tag).then(() => this.rerender(pop, file));
        });
      });
    }
  }
  renderChips(container, tags, filePath) {
    if (tags.length === 0) {
      container.createEl("p", { cls: "pdf-tags-no-tags", text: "No tags yet." });
      return;
    }
    tags.forEach((tag) => {
      const chip = container.createEl("span", { cls: "pdf-tags-chip" });
      chip.createEl("span", { text: `#${tag}`, cls: "pdf-tags-chip-label" });
      const removeBtn = chip.createEl("button", {
        cls: "pdf-tags-chip-remove",
        attr: { "aria-label": `Remove tag ${tag}` }
      });
      (0, import_obsidian2.setIcon)(removeBtn, "x");
      removeBtn.addEventListener("click", () => {
        const pop = container.closest(".pdf-tags-popover");
        void this.plugin.removeTag(filePath, tag).then(() => {
          if (pop instanceof HTMLElement)
            void this.rerender(pop, this.file);
        });
      });
    });
  }
};

// src/PdfToolbarInjector.ts
var INJECTED_ATTR = "data-pdf-tags-injected";
var PdfToolbarInjector = class {
  constructor(plugin) {
    /** Map from toolbarRightEl → its MutationObserver, so we can disconnect on unload */
    this.observers = /* @__PURE__ */ new Map();
    this.plugin = plugin;
  }
  async injectLeaf(leaf) {
    var _a;
    const view = leaf.view;
    if (((_a = view == null ? void 0 : view.getViewType) == null ? void 0 : _a.call(view)) !== "pdf")
      return;
    const viewerComponent = view.viewer;
    if (!viewerComponent)
      return;
    const doInject = (child) => this.injectChild(child, leaf);
    if (viewerComponent.child) {
      doInject(viewerComponent.child);
    } else if (typeof viewerComponent.then === "function") {
      const child = await new Promise((resolve) => {
        viewerComponent.then(resolve);
      });
      doInject(child);
    }
  }
  injectChild(child, leaf) {
    var _a;
    const toolbarRightEl = (_a = child == null ? void 0 : child.toolbar) == null ? void 0 : _a.toolbarRightEl;
    if (!toolbarRightEl)
      return;
    this.injectButton(toolbarRightEl, leaf);
    if (!this.observers.has(toolbarRightEl)) {
      const obs = new MutationObserver(() => {
        if (!toolbarRightEl.querySelector(`[${INJECTED_ATTR}]`)) {
          this.injectButton(toolbarRightEl, leaf);
        }
      });
      obs.observe(toolbarRightEl, { childList: true });
      this.observers.set(toolbarRightEl, obs);
    }
  }
  injectButton(toolbarRightEl, leaf) {
    if (toolbarRightEl.querySelector(`[${INJECTED_ATTR}]`))
      return;
    const btn = toolbarRightEl.createEl("button", {
      cls: "pdf-toolbar-button clickable-icon pdf-tags-toolbar-btn",
      attr: {
        [INJECTED_ATTR]: "true",
        "aria-label": "Edit PDF tags"
      }
    });
    (0, import_obsidian3.setIcon)(btn, "tag");
    let activePopover = null;
    btn.addEventListener("click", (evt) => {
      var _a;
      evt.stopPropagation();
      const view = leaf.view;
      const file = (_a = view.file) != null ? _a : null;
      if (!file)
        return;
      if (activePopover) {
        activePopover.close();
        activePopover = null;
        return;
      }
      activePopover = new TagPopover(this.plugin, file, btn, () => {
        activePopover = null;
      });
      activePopover.open();
    });
  }
  async injectAll() {
    const leaves = this.plugin.app.workspace.getLeavesOfType("pdf");
    for (const leaf of leaves) {
      await this.injectLeaf(leaf);
    }
  }
  destroy() {
    this.observers.forEach((obs) => obs.disconnect());
    this.observers.clear();
  }
};

// src/main.ts
var PdfTagsPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.removeFromUserIgnoreFilters(this.settings.companionFolder);
    this.injector = new PdfToolbarInjector(this);
    this.app.workspace.onLayoutReady(() => {
      void this.injector.injectAll();
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (leaf)
          void this.injector.injectLeaf(leaf);
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        void this.injector.injectAll();
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian4.TFile && file.extension === "pdf") {
          menu.addItem((item) => {
            item.setTitle("Open PDF in new tab to manage tags").setIcon("tag").onClick(async () => {
              const leaf = this.app.workspace.getLeaf("tab");
              await leaf.openFile(file);
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian4.TFile && file.extension === "pdf") {
          void this.handlePdfRename(file, oldPath);
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian4.TFile && file.extension === "pdf") {
          void this.handlePdfDelete(file);
        }
      })
    );
    this.addSettingTab(new PdfTagsSettingTab(this.app, this));
  }
  onunload() {
    this.injector.destroy();
  }
  // ─── Settings ────────────────────────────────────────────────────────────────
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data != null ? data : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ─── Folder visibility (CSS only) ────────────────────────────────────────────
  removeFromUserIgnoreFilters(folder) {
    const vault = this.app.vault;
    const existing = vault.getConfig("userIgnoreFilters");
    const filters = Array.isArray(existing) ? existing : [];
    const normalized = (0, import_obsidian4.normalizePath)(folder);
    const updated = filters.filter((f) => f !== normalized);
    if (updated.length !== filters.length) {
      vault.setConfig("userIgnoreFilters", updated.length ? updated : null);
    }
  }
  // ─── Companion file helpers ──────────────────────────────────────────────────
  companionPathFor(pdfPath) {
    const name = pdfPath.replace(/\//g, "__").replace(/\.pdf$/i, "") + ".md";
    return (0, import_obsidian4.normalizePath)(`${this.settings.companionFolder}/${name}`);
  }
  async ensureFolder() {
    const folder = (0, import_obsidian4.normalizePath)(this.settings.companionFolder);
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      await this.app.vault.createFolder(folder);
    }
  }
  async getTagsForFile(pdfPath) {
    const companionPath = this.companionPathFor(pdfPath);
    const file = this.app.vault.getAbstractFileByPath(companionPath);
    if (!(file instanceof import_obsidian4.TFile))
      return [];
    let result = [];
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      const raw = fm["tags"];
      if (Array.isArray(raw))
        result = raw.map(String);
      else if (typeof raw === "string")
        result = [raw];
    });
    return result;
  }
  async writeTagsForFile(pdfPath, tags) {
    var _a;
    await this.ensureFolder();
    const companionPath = this.companionPathFor(pdfPath);
    const existing = this.app.vault.getAbstractFileByPath(companionPath);
    let file;
    if (existing instanceof import_obsidian4.TFile) {
      file = existing;
    } else {
      const pdfName = (_a = pdfPath.split("/").pop()) != null ? _a : pdfPath;
      file = await this.app.vault.create(companionPath, `[[${pdfName}]]
`);
    }
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm["tags"] = tags;
    });
  }
  async addTag(pdfPath, tag) {
    const tags = await this.getTagsForFile(pdfPath);
    if (tags.includes(tag))
      return;
    await this.writeTagsForFile(pdfPath, [...tags, tag]);
  }
  async removeTag(pdfPath, tag) {
    const tags = await this.getTagsForFile(pdfPath);
    await this.writeTagsForFile(pdfPath, tags.filter((t) => t !== tag));
  }
  getAllVaultTags() {
    var _a, _b;
    const cache = this.app.metadataCache;
    const tagMap = (_b = (_a = cache.getTags) == null ? void 0 : _a.call(cache)) != null ? _b : {};
    return Object.keys(tagMap).map((t) => t.replace(/^#/, "")).sort();
  }
  // ─── Rename / Delete sync ────────────────────────────────────────────────────
  async handlePdfRename(file, oldPath) {
    const oldCompanion = this.companionPathFor(oldPath);
    const oldFile = this.app.vault.getAbstractFileByPath(oldCompanion);
    if (!(oldFile instanceof import_obsidian4.TFile))
      return;
    const newCompanion = this.companionPathFor(file.path);
    await this.app.fileManager.renameFile(oldFile, newCompanion);
  }
  async handlePdfDelete(file) {
    const companionPath = this.companionPathFor(file.path);
    const companion = this.app.vault.getAbstractFileByPath(companionPath);
    if (companion instanceof import_obsidian4.TFile) {
      await this.app.fileManager.trashFile(companion);
    }
  }
};
